import { PublicEventBrowseInput, PublicEventCreateInput, PublicEventLocationSuggestion, PublicEventPromotionInput, PublicEventUpdateInput } from '@/types';
export declare class PublicEventService {
    private prisma;
    createPublicEvent(organizerId: string, data: PublicEventCreateInput): Promise<{
        organizer: {
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        promotionPayments: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import("@prisma/client").$Enums.PromotionPaymentStatus;
            regionRadiusMiles: number;
            currency: string;
            amount: import("@prisma/client/runtime/library").Decimal;
            regionCity: string | null;
            regionState: string | null;
            regionCountry: string | null;
            provider: string;
            paidAt: Date | null;
            organizerId: string;
            publicEventId: string;
            providerCheckoutId: string | null;
            providerPaymentIntentId: string | null;
            checkoutUrl: string | null;
            startsAt: Date;
            endsAt: Date;
        }[];
    } & {
        description: string | null;
        id: string;
        city: string;
        state: string | null;
        country: string;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        createdAt: Date;
        updatedAt: Date;
        status: import("@prisma/client").$Enums.PublicEventStatus;
        startDate: Date;
        endDate: Date | null;
        coverImage: string | null;
        title: string;
        venueName: string | null;
        addressLine: string | null;
        regionRadiusMiles: number;
        currency: string;
        publishedAt: Date | null;
        promotionStartsAt: Date | null;
        promotionEndsAt: Date | null;
        organizerId: string;
    }>;
    getPublicEventForUser(publicEventId: string, userId: string): Promise<({
        organizer: {
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        promotionPayments: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import("@prisma/client").$Enums.PromotionPaymentStatus;
            regionRadiusMiles: number;
            currency: string;
            amount: import("@prisma/client/runtime/library").Decimal;
            regionCity: string | null;
            regionState: string | null;
            regionCountry: string | null;
            provider: string;
            paidAt: Date | null;
            organizerId: string;
            publicEventId: string;
            providerCheckoutId: string | null;
            providerPaymentIntentId: string | null;
            checkoutUrl: string | null;
            startsAt: Date;
            endsAt: Date;
        }[];
    } & {
        description: string | null;
        id: string;
        city: string;
        state: string | null;
        country: string;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        createdAt: Date;
        updatedAt: Date;
        status: import("@prisma/client").$Enums.PublicEventStatus;
        startDate: Date;
        endDate: Date | null;
        coverImage: string | null;
        title: string;
        venueName: string | null;
        addressLine: string | null;
        regionRadiusMiles: number;
        currency: string;
        publishedAt: Date | null;
        promotionStartsAt: Date | null;
        promotionEndsAt: Date | null;
        organizerId: string;
    }) | null>;
    updatePublicEvent(publicEventId: string, organizerId: string, data: PublicEventUpdateInput): Promise<{
        organizer: {
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        promotionPayments: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import("@prisma/client").$Enums.PromotionPaymentStatus;
            regionRadiusMiles: number;
            currency: string;
            amount: import("@prisma/client/runtime/library").Decimal;
            regionCity: string | null;
            regionState: string | null;
            regionCountry: string | null;
            provider: string;
            paidAt: Date | null;
            organizerId: string;
            publicEventId: string;
            providerCheckoutId: string | null;
            providerPaymentIntentId: string | null;
            checkoutUrl: string | null;
            startsAt: Date;
            endsAt: Date;
        }[];
    } & {
        description: string | null;
        id: string;
        city: string;
        state: string | null;
        country: string;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        createdAt: Date;
        updatedAt: Date;
        status: import("@prisma/client").$Enums.PublicEventStatus;
        startDate: Date;
        endDate: Date | null;
        coverImage: string | null;
        title: string;
        venueName: string | null;
        addressLine: string | null;
        regionRadiusMiles: number;
        currency: string;
        publishedAt: Date | null;
        promotionStartsAt: Date | null;
        promotionEndsAt: Date | null;
        organizerId: string;
    }>;
    createPromotionCheckout(publicEventId: string, organizerId: string, data: PublicEventPromotionInput): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import("@prisma/client").$Enums.PromotionPaymentStatus;
        regionRadiusMiles: number;
        currency: string;
        amount: import("@prisma/client/runtime/library").Decimal;
        regionCity: string | null;
        regionState: string | null;
        regionCountry: string | null;
        provider: string;
        paidAt: Date | null;
        organizerId: string;
        publicEventId: string;
        providerCheckoutId: string | null;
        providerPaymentIntentId: string | null;
        checkoutUrl: string | null;
        startsAt: Date;
        endsAt: Date;
    }>;
    confirmPromotionPayment(publicEventId: string, organizerId: string, paymentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import("@prisma/client").$Enums.PromotionPaymentStatus;
        regionRadiusMiles: number;
        currency: string;
        amount: import("@prisma/client/runtime/library").Decimal;
        regionCity: string | null;
        regionState: string | null;
        regionCountry: string | null;
        provider: string;
        paidAt: Date | null;
        organizerId: string;
        publicEventId: string;
        providerCheckoutId: string | null;
        providerPaymentIntentId: string | null;
        checkoutUrl: string | null;
        startsAt: Date;
        endsAt: Date;
    }>;
    publishPublicEvent(publicEventId: string, organizerId: string): Promise<{
        organizer: {
            id: string;
            name: string;
            avatarUrl: string | null;
        };
        promotionPayments: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import("@prisma/client").$Enums.PromotionPaymentStatus;
            regionRadiusMiles: number;
            currency: string;
            amount: import("@prisma/client/runtime/library").Decimal;
            regionCity: string | null;
            regionState: string | null;
            regionCountry: string | null;
            provider: string;
            paidAt: Date | null;
            organizerId: string;
            publicEventId: string;
            providerCheckoutId: string | null;
            providerPaymentIntentId: string | null;
            checkoutUrl: string | null;
            startsAt: Date;
            endsAt: Date;
        }[];
    } & {
        description: string | null;
        id: string;
        city: string;
        state: string | null;
        country: string;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        createdAt: Date;
        updatedAt: Date;
        status: import("@prisma/client").$Enums.PublicEventStatus;
        startDate: Date;
        endDate: Date | null;
        coverImage: string | null;
        title: string;
        venueName: string | null;
        addressLine: string | null;
        regionRadiusMiles: number;
        currency: string;
        publishedAt: Date | null;
        promotionStartsAt: Date | null;
        promotionEndsAt: Date | null;
        organizerId: string;
    }>;
    browsePublicEvents(input: PublicEventBrowseInput): Promise<any[]>;
    listBrowseLocations(city: string, limit?: number): Promise<PublicEventLocationSuggestion[]>;
    private assertOrganizer;
    private defaultInclude;
}
export declare const publicEventService: PublicEventService;
//# sourceMappingURL=public-event.service.d.ts.map