export declare class UserService {
    getUserById(id: string): Promise<{
        settings: {
            userId: string;
            friendRequestSource: import("@prisma/client").$Enums.FriendRequestSource;
            emailTripInvites: boolean;
            emailPaymentRequests: boolean;
            emailVotingReminders: boolean;
            emailTripReminders: boolean;
            emailMessages: boolean;
            pushTripInvites: boolean;
            pushPaymentRequests: boolean;
            pushVotingReminders: boolean;
            pushTripReminders: boolean;
            pushMessages: boolean;
            inAppAll: boolean;
        } | null;
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
        phone: string | null;
        venmo: string | null;
        paypal: string | null;
        zelle: string | null;
        cashapp: string | null;
        createdAt: Date;
    } | null>;
    getUserByEmail(email: string): Promise<{
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
        phone: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        locationSource: import("@prisma/client").$Enums.UserLocationSource | null;
        venmo: string | null;
        paypal: string | null;
        zelle: string | null;
        cashapp: string | null;
        passwordHash: string | null;
        createdAt: Date;
        updatedAt: Date;
        emailNotificationsEnabled: boolean;
    } | null>;
    createUser(data: {
        email: string;
        name: string;
        password?: string;
        avatarUrl?: string;
        phone?: string;
    }): Promise<{
        settings: {
            userId: string;
            friendRequestSource: import("@prisma/client").$Enums.FriendRequestSource;
            emailTripInvites: boolean;
            emailPaymentRequests: boolean;
            emailVotingReminders: boolean;
            emailTripReminders: boolean;
            emailMessages: boolean;
            pushTripInvites: boolean;
            pushPaymentRequests: boolean;
            pushVotingReminders: boolean;
            pushTripReminders: boolean;
            pushMessages: boolean;
            inAppAll: boolean;
        } | null;
    } & {
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
        phone: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        locationSource: import("@prisma/client").$Enums.UserLocationSource | null;
        venmo: string | null;
        paypal: string | null;
        zelle: string | null;
        cashapp: string | null;
        passwordHash: string | null;
        createdAt: Date;
        updatedAt: Date;
        emailNotificationsEnabled: boolean;
    }>;
    createOAuthUser(data: {
        email: string;
        name: string;
        avatarUrl?: string;
        provider: string;
        providerId?: string;
    }): Promise<{
        settings: {
            userId: string;
            friendRequestSource: import("@prisma/client").$Enums.FriendRequestSource;
            emailTripInvites: boolean;
            emailPaymentRequests: boolean;
            emailVotingReminders: boolean;
            emailTripReminders: boolean;
            emailMessages: boolean;
            pushTripInvites: boolean;
            pushPaymentRequests: boolean;
            pushVotingReminders: boolean;
            pushTripReminders: boolean;
            pushMessages: boolean;
            inAppAll: boolean;
        } | null;
    } & {
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
        phone: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        locationSource: import("@prisma/client").$Enums.UserLocationSource | null;
        venmo: string | null;
        paypal: string | null;
        zelle: string | null;
        cashapp: string | null;
        passwordHash: string | null;
        createdAt: Date;
        updatedAt: Date;
        emailNotificationsEnabled: boolean;
    }>;
    updateUser(userId: string, data: {
        name?: string;
        avatarUrl?: string;
        phone?: string;
        city?: string;
        state?: string;
        country?: string;
        latitude?: number | null;
        longitude?: number | null;
        locationSource?: 'PROFILE' | 'BROWSER' | 'IP_INFERRED' | null;
        venmo?: string;
        paypal?: string;
        zelle?: string;
        cashapp?: string;
    }): Promise<{
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
        phone: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        locationSource: import("@prisma/client").$Enums.UserLocationSource | null;
        venmo: string | null;
        paypal: string | null;
        zelle: string | null;
        cashapp: string | null;
        passwordHash: string | null;
        createdAt: Date;
        updatedAt: Date;
        emailNotificationsEnabled: boolean;
    }>;
    updatePassword(userId: string, currentPassword: string, newPassword: string): Promise<{
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
        phone: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        locationSource: import("@prisma/client").$Enums.UserLocationSource | null;
        venmo: string | null;
        paypal: string | null;
        zelle: string | null;
        cashapp: string | null;
        passwordHash: string | null;
        createdAt: Date;
        updatedAt: Date;
        emailNotificationsEnabled: boolean;
    }>;
    verifyPassword(email: string, password: string): Promise<{
        id: string;
        email: string;
        name: string;
        avatarUrl: string | null;
    } | null>;
    getSettings(userId: string): Promise<{
        userId: string;
        friendRequestSource: import("@prisma/client").$Enums.FriendRequestSource;
        emailTripInvites: boolean;
        emailPaymentRequests: boolean;
        emailVotingReminders: boolean;
        emailTripReminders: boolean;
        emailMessages: boolean;
        pushTripInvites: boolean;
        pushPaymentRequests: boolean;
        pushVotingReminders: boolean;
        pushTripReminders: boolean;
        pushMessages: boolean;
        inAppAll: boolean;
    } | null>;
    updateSettings(userId: string, data: {
        friendRequestSource?: 'ANYONE' | 'TRIP_MEMBERS';
        emailTripInvites?: boolean;
        emailPaymentRequests?: boolean;
        emailVotingReminders?: boolean;
        emailTripReminders?: boolean;
        emailMessages?: boolean;
        pushTripInvites?: boolean;
        pushPaymentRequests?: boolean;
        pushVotingReminders?: boolean;
        pushTripReminders?: boolean;
        pushMessages?: boolean;
        inAppAll?: boolean;
    }): Promise<{
        userId: string;
        friendRequestSource: import("@prisma/client").$Enums.FriendRequestSource;
        emailTripInvites: boolean;
        emailPaymentRequests: boolean;
        emailVotingReminders: boolean;
        emailTripReminders: boolean;
        emailMessages: boolean;
        pushTripInvites: boolean;
        pushPaymentRequests: boolean;
        pushVotingReminders: boolean;
        pushTripReminders: boolean;
        pushMessages: boolean;
        inAppAll: boolean;
    }>;
    generatePasswordResetToken(email: string): Promise<{
        token: string;
        userId: string;
    }>;
    resetPassword(token: string, newPassword: string): Promise<boolean>;
}
export declare const userService: UserService;
//# sourceMappingURL=user.service.d.ts.map